name: flutter_timerman
description: Timerman app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  intl: ^0.17.0

  json_serializable: ^6.1.4
  pull_to_refresh: ^2.0.0



dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  #dart_code_metrics: ^4.9.1
  #analyzer: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ">=1.0.0 <1.1.1"
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0


flutter:
  uses-material-design: true
  generate: true
