name: flutter_timerman
description: Timerman app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^4.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  intl: ^0.17.0

  json_annotation: ^4.4.0
  
  pull_to_refresh: ^2.0.0
  flutterfire_ui: ^0.3.4
  shared_preferences: ^2.0.13
  string_validator: ^0.3.0
  email_validator: ^2.0.1
  page_transition: ^2.0.5
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  rxdart: ^0.27.3
  image_picker: ^0.8.5
  firebase_storage: ^10.2.12
  flutter_image_compress: ^1.1.0
  go_router: ^3.0.7
#background_location_tracker

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  #dart_code_metrics: ^4.9.1
  #analyzer: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ">=1.0.0 <1.1.1"
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2


flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/images/background.jpg
   - assets/images/timerman.png
   - assets/images/event_1.jpg
   - assets/images/event_2.jpg
   - assets/images/event_3.jpg
   - assets/images/event_4.jpg
   